import { PlatformLocation } from '@angular/common';
import { EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ScrollToService } from '@nicky-lenaers/ngx-scroll-to';
import { WindowRefService } from '../window-ref/window-ref.service';
import { IScrollEventListener, ScrollEventService } from './scroll-event.service';
import { SectionModel } from './section.model';
export declare class FullpageComponent implements OnInit, OnDestroy, IScrollEventListener {
    private scrollToService;
    private route;
    private router;
    private document;
    private windowRef;
    private scrollEventService;
    private platformLocation;
    static ignoreWhenFocused: string[];
    static eventListenerKey: string;
    static activeClass: string;
    static scrollingCompleteSensitivity: number;
    window: any;
    activeSection: any;
    previousSectionIndex: number;
    sectionIndex: number;
    scrolling: boolean;
    sectionScrolling: boolean;
    sectionScrollingTimeout: any;
    sections: SectionModel[];
    lockScrolling: boolean;
    scrollSensitivity: number;
    sectionChange: EventEmitter<string>;
    constructor(scrollToService: ScrollToService, route: ActivatedRoute, router: Router, document: any, windowRef: WindowRefService, scrollEventService: ScrollEventService, platformLocation: PlatformLocation);
    ngOnInit(): void;
    ngOnDestroy(): void;
    scroll(index: number): void;
    private switchSections;
    private invokeScroll;
    scrollUp(event: Event): void;
    scrollDown(event: Event): void;
    private activateSectionScrolling;
    private canScroll;
    checkFocus(): boolean;
    private canScrollUp;
    private canScrollDown;
    private calcSectionPosition;
    fullpageWindowScroll(event: WheelEvent): void;
    fullpageArrowUpEvent(event: KeyboardEvent): void;
    fullpageArrowDownEvent(event: KeyboardEvent): void;
    fullpageResizeEvent(): void;
}
